<?php
/**
 * Class EventsTest
 *
 * @package Sift_Decisions
 */

// phpcs:disable Universal.Arrays.DisallowShortArraySyntax.Found

use WPCOMSpecialProjects\SiftDecisions\WooCommerce_Actions\Events;

/**
 * Events test case.
 */
class EventsTest extends WP_UnitTestCase {

	/**
	 * Set up the test case.
	 *
	 * @return void
	 */
	public function set_up() {
		parent::set_up(); // TODO: Change the autogenerated stub
		Events::$to_send = [];
	}

	/**
	 * Tear down the test case.
	 *
	 * @return void
	 */
	public function tear_down() {
		Events::$to_send = [];
		parent::tear_down(); // TODO: Change the autogenerated stub
	}

	public static function filter_events( $event_types = [] ) {
		//$return = [];
		//foreach ( Events::$to_send as $event ) {
		//	if ( in_array( $event['event'], $events, true ) ) {
		//		$return[] = $event;
		//	}
		//}
		//return $return;
		return array_filter( Events::$to_send, fn ( $event ) => in_array( $event['event'], $event_types, true ) );
	}


	/**
	 * Test that the add_to_cart event is triggered.
	 *
	 * @return void
	 */
	public function test_add_item_to_cart() {
		do_action( 'woocommerce_add_to_cart', 1 );
		$this->assertContains( 'add_item_to_cart', WPCOMSpecialProjects\SiftDecisions\WooCommerce_Actions\Events::$to_send );
	}
}
